// Autogenerated by Thrift Compiler (0.9.3)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package notestore

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"github.com/dragonfax/evernote-sdk-go/errors"
	"github.com/dragonfax/evernote-sdk-go/limits"
	"github.com/dragonfax/evernote-sdk-go/types"
	"github.com/dragonfax/evernote-sdk-go/userstore"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = userstore.GoUnusedProtection__
var _ = types.GoUnusedProtection__
var _ = errors.GoUnusedProtection__
var _ = limits.GoUnusedProtection__

func init() {
}
